# Generated by Django 5.2.3 on 2025-07-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Total activity duration in minutes', null=True)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('program_level', models.CharField(blank=True, choices=[('beg', 'Beginner'), ('adv', 'Advanced'), ('pro', 'Professional')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('waiting', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['activity__day_of_week', 'activity__start_time'],
            },
        ),
    ]
