# Generated by Django 5.2.3 on 2025-07-01 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('youtube_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Reps for the current exercise', null=True)),
                ('duration', models.DurationField(blank=True, help_text='Optional exercise duration (e.g., 00:05:00 for 5 minutes)', null=True)),
                ('program_level', models.CharField(blank=True, choices=[('beg', 'Beginner'), ('adv', 'Advanced'), ('pro', 'Professional')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'program_level', 'order'), name='unique_order_per_category_level')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs')], max_length=10)),
                ('program_level', models.CharField(blank=True, choices=[('beg', 'Beginner'), ('adv', 'Advanced'), ('pro', 'Professional')], max_length=20, null=True)),
                ('completed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, help_text='Total workout duration', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercises_completed', models.ManyToManyField(blank=True, related_name='workout_sessions', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_date'],
                'indexes': [models.Index(fields=['user', 'completed_date'], name='workouts_wo_user_id_94f8b0_idx')],
            },
        ),
    ]
